root: Item
children:
  - modifiers?: [ItemModifier]
  - action?: ItemAction
  - alternate?: ItemAction
  - description?: String
  - additional_text?: [String]
  - index?: int
rules:
  - for: ItemModifier
    parser: "**/*ItemModifier.dokedef.yaml"
    children: [ItemEffect]

  - for: ItemAction
    parser: "**/*ItemAction.dokedef.yaml"
    children: [ActionComponent]
  
  - for: ActionComponent
    parser : "**/*ActionComponent.dokedef.yaml"
    children: [ActionComponent]
